import { GameSets, GroupTypes } from "../../../types";
import { Character } from "../character";

export class Maid extends Character {
    readonly Id = "maid";
    readonly Group = GroupTypes.Passive;
    readonly Game = GameSets.Characters;
    override readonly Description = [
        { title: $localize`:@@character-description-general:Allgemein`, description: $localize`:@@character-description-maid-general:Bevor die Karte eines Mitspielers, welcher durch die Wahl des Dorfes aus dem Spiel ausgeschieden ist, vom Spielleiter aufgedeckt wird, darf die Ergebene Magd sich offenbaren, indem sie ihre Karte aufdeckt. In diesem Falle verliert der Spieler der Magd seine Karte und erhält im Gegenzug den Charakter des Spielers, der ausscheidet. Dieser Charakter wird den anderen Spielern nicht gezeigt und verbleibt im Besitz des Spielers, der ehemals die Magd verkörpert hat, bis dieser ausscheidet oder das Spiel endet.` },
        { title: $localize`:@@character-description-attention:Achtung`, description: $localize`:@@character-description-maid-attention:Gehört die Magd zum Liebespaar, hat sie diese Entscheidung nicht mehr. Die Macht der Liebe ist größer als der Wille, den Charakter zu ändern.` },
        { title: $localize`:@@character-description-hint-for-narrator:Tipp für den Spielleiter`, description: $localize`:@@character-description-maid-hint-for-narrator:Lass dir Zeit, bevor du den Spielern den ausgeschiedenen Charakter zeigst, damit du der Magd die Möglichkeit gibst, sich zu offenbaren. Übernimmt sie einen Charakter mit Spezialfähigkeiten, so wird sie die folgenden Nächte entsprechend des Charakters aufgerufen. Vor allem in der ersten Nacht solltest du die ehemalige Magd still darauf hinweisen, damit sie sich an ihre neue Rolle gewöhnen kann. Grundsätzlich gilt, dass sämtliche Sonderfähigkeiten des Charakters, den die Ergebene Magd erhält, erneuert werden und dieser gespielt wird, als wäre es die erste Nacht. Dafür wird jeder Effekt, der möglicherweise vorher auf dem ausgeschiedenen Spieler lag, annulliert.` },
        { title: $localize`:@@character-description-explanations:Erläuterungen`, description: $localize`:@@character-description-maid-explanations:Wenn der ausgeschiedene Spieler infiziert, verliebt, verzaubert, Hauptmann, Büttel oder Amor war bzw. ist, wird die ehemalige Ergebene Magd dies nicht. Wenn die ehemalige Ergebene Magd ver- zaubert, Hauptmann oder Büttel war, ist sie dies nun nicht mehr. Wenn die ehemalige Ergebene Magd: infiziert war, ist sie dies weiterhin; Flötenspieler wird, teilt der Spielleiter diesem neuen Flötenspieler mit, welche Spieler zuvor verzaubert worden sind; Gaukler, Büttel oder Zigeunerin wird: Es werden keine zusätzlichen Karten verteilt; es werden lediglich die noch nicht eingesetzten Karten weiter verwendet.` }];
}